### ISSUE TITLE
O aviso de gato cadastrado precisa aparecer na listagem de gatos, após o cadastro

### ISSUE THREAD

**Issue by viniciusgferreira** [viniciusgferreira/creche-batatinha#19]
De acordo com o protótipo, a mudança de página após o cadastro é instantânea, mostrando a nova listagem com o gato novo cadastrado e o aviso de sucesso.

**Comment by viniciusgferreira** [comment]
@chrixtianny Pode resolver essa issue?

**Comment by chrixtianny** [comment]
> @chrixtianny Pode resolver essa issue?

Pode deixar comigo
